name = input("Please enter your name: ")
age = input("Please enter your age in years: ")
house_number = input("Please enter your house number: ")
street_name = input("Please enter your street name: ")
print("This is {}. They are {} years old and live at house number {} on {}.".format(name, age, house_number, street_name))